[package]
name = "memfaultc-sys"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
libc = "0.2.138"

[build-dependencies]
cc = "1.0.83"
pkg-config = "0.3"
walkdir = "2"

[features]
default = []
coredump = []
systemd = []
swupdate = []
